-- 75_LANCAMENTOS_CONTABEIS_PARTIDAS_DOBRADAS.sql
-- Escrituração contábil inicial: cabeçalho + partidas, revisão e contabilização protegida.
begin;

create table if not exists public.contabil_lancamentos (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  exercicio_id uuid references public.contabil_exercicios(id) on delete restrict,
  data date not null,
  referencia text not null check (referencia ~ '^[0-9]{4}-[0-9]{2}$'),
  numero bigint generated by default as identity,
  historico text not null,
  documento text,
  origem_tipo text not null default 'manual' check (origem_tipo in ('manual','receita','despesa','transferencia','importacao')),
  origem_id uuid,
  status text not null default 'rascunho' check (status in ('rascunho','revisao','contabilizado','cancelado')),
  contabilizado_em timestamptz,
  contabilizado_por uuid references auth.users(id),
  observacoes text,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (empresa_id, origem_tipo, origem_id)
);

create table if not exists public.contabil_partidas (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  lancamento_id uuid not null references public.contabil_lancamentos(id) on delete cascade,
  conta_contabil_id uuid not null references public.contabil_plano_contas(id) on delete restrict,
  tipo text not null check (tipo in ('debito','credito')),
  valor numeric(14,2) not null check (valor > 0),
  historico_complementar text,
  ordem integer not null default 1,
  created_at timestamptz not null default now()
);

create index if not exists idx_contabil_lancamentos_empresa_data on public.contabil_lancamentos(empresa_id, data desc);
create index if not exists idx_contabil_lancamentos_status on public.contabil_lancamentos(empresa_id, status, referencia);
create index if not exists idx_contabil_partidas_lancamento on public.contabil_partidas(lancamento_id, ordem);
create index if not exists idx_contabil_partidas_conta on public.contabil_partidas(empresa_id, conta_contabil_id);

create or replace function public.validar_partida_contabil_mesma_empresa()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare lanc_empresa uuid; conta_empresa uuid; conta_analitica boolean;
begin
  select empresa_id into lanc_empresa from public.contabil_lancamentos where id = new.lancamento_id;
  select empresa_id, analitica into conta_empresa, conta_analitica from public.contabil_plano_contas where id = new.conta_contabil_id;
  if lanc_empresa is null or conta_empresa is null or lanc_empresa <> new.empresa_id or conta_empresa <> new.empresa_id then
    raise exception 'Lançamento, partida e conta contábil devem pertencer à mesma empresa.';
  end if;
  if conta_analitica is not true then raise exception 'Somente contas analíticas aceitam lançamentos.'; end if;
  return new;
end;
$$;

drop trigger if exists trg_validar_partida_contabil_empresa on public.contabil_partidas;
create trigger trg_validar_partida_contabil_empresa before insert or update on public.contabil_partidas
for each row execute function public.validar_partida_contabil_mesma_empresa();

create or replace function public.contabilizar_lancamento(p_lancamento_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_empresa uuid; v_status text; v_debitos numeric(14,2); v_creditos numeric(14,2);
begin
  select empresa_id, status into v_empresa, v_status from public.contabil_lancamentos where id = p_lancamento_id for update;
  if v_empresa is null then raise exception 'Lançamento contábil não encontrado.'; end if;
  if not (public.is_master() or (public.is_ativo() and v_empresa = public.current_empresa_id() and public.current_role() in ('admin','tesoureiro'))) then
    raise exception 'Sem permissão para contabilizar este lançamento.';
  end if;
  if v_status in ('contabilizado','cancelado') then raise exception 'Lançamento já finalizado.'; end if;
  select coalesce(sum(valor) filter (where tipo='debito'),0), coalesce(sum(valor) filter (where tipo='credito'),0)
    into v_debitos, v_creditos from public.contabil_partidas where lancamento_id = p_lancamento_id;
  if v_debitos <= 0 or v_creditos <= 0 or v_debitos <> v_creditos then
    raise exception 'Lançamento desequilibrado. Débitos (%) e créditos (%) devem ser iguais e maiores que zero.', v_debitos, v_creditos;
  end if;
  update public.contabil_lancamentos set status='contabilizado', contabilizado_em=now(), contabilizado_por=auth.uid(), updated_at=now()
   where id=p_lancamento_id;
end;
$$;

alter table public.contabil_lancamentos enable row level security;
alter table public.contabil_partidas enable row level security;


do $$
declare t text;
begin
  foreach t in array array['contabil_lancamentos','contabil_partidas'] loop
    execute format('drop policy if exists %I on public.%I', t || '_select', t);
    execute format('drop policy if exists %I on public.%I', t || '_insert', t);
    execute format('drop policy if exists %I on public.%I', t || '_update', t);
    execute format('drop policy if exists %I on public.%I', t || '_delete', t);
    execute format('create policy %I on public.%I for select using (public.is_master() or (public.is_ativo() and empresa_id = public.current_empresa_id()))', t || '_select', t);
    execute format('create policy %I on public.%I for insert with check (public.is_master() or (public.is_ativo() and empresa_id = public.current_empresa_id() and public.current_role() in (''admin'',''tesoureiro'')))', t || '_insert', t);
    execute format('create policy %I on public.%I for update using (public.is_master() or (public.is_ativo() and empresa_id = public.current_empresa_id() and public.current_role() in (''admin'',''tesoureiro''))) with check (public.is_master() or (public.is_ativo() and empresa_id = public.current_empresa_id() and public.current_role() in (''admin'',''tesoureiro'')))', t || '_update', t);
    execute format('create policy %I on public.%I for delete using (public.is_master() or (public.is_ativo() and empresa_id = public.current_empresa_id() and public.current_role() = ''admin''))', t || '_delete', t);
  end loop;
end $$;

commit;
